FROM mongo:6

# This Dockerfile allows for customization of the MongoDB image.
# You can add initialization scripts or configuration files here.
# For example, to initialize a database with a user:
# COPY mongo-init.js /docker-entrypoint-initdb.d/
